export interface IScreeningProfileHttpResponse {
    id: string;
    name: string;
    created: string;
    modified: string;
    country_check_unknown_severity: string;
    url: string;
    company_blacklists: string;
    port_blacklists: string;
    country_blacklists: string;
    ship_blacklists: string;
    company_check_prior_months: number;
    company_check_prior_months_severity: string;
    company_check_severity: string;
    company_check_severity_technical_manager: string;
    company_check_severity_technical_manager_sdn: string;
    company_check_severity_technical_manager_generic: string;
    company_check_severity_group_beneficial_owner: string;
    company_check_severity_group_beneficial_owner_sdn: string;
    company_check_severity_group_beneficial_owner_generic: string;
    company_check_severity_ship_manager: string;
    company_check_severity_ship_manager_sdn: string;
    company_check_severity_ship_manager_generic: string;
    company_check_severity_operator: string;
    company_check_severity_operator_sdn: string;
    company_check_severity_operator_generic: string;
    company_check_severity_registered_owner: string;
    company_check_severity_registered_owner_sdn: string;
    company_check_severity_registered_owner_generic: string;
    country_check_severity: string;
    ship_sanction_check_severity: string;
    ship_sanction_check_severity_sdn: string;
    ship_sanction_check_severity_generic: string;
    ship_sanction_prior_months: 3;
    ship_sanction_prior_months_severity: string;
    port_visit_severity: string;
    no_ais_position_severity: string;
    zone_severity: string;
    ship_inspection_detained: string;
    ship_inspection_deficiency: string;
}

export class ScreeningProfile {
    id: string;
    name: string;
    created: Date;
    modified: Date;
    url: string;
    company_blacklists: string;
    port_blacklists: string;
    country_blacklists: string;
    ship_blacklists: string;
    company_check_prior_months: number;
    company_check_prior_months_severity: string;
    company_check_severity: string;
    company_check_severity_technical_manager: string;
    company_check_severity_technical_manager_sdn: string;
    company_check_severity_technical_manager_generic: string;
    company_check_severity_group_beneficial_owner: string;
    company_check_severity_group_beneficial_owner_sdn: string;
    company_check_severity_group_beneficial_owner_generic: string;
    company_check_severity_ship_manager: string;
    company_check_severity_ship_manager_sdn: string;
    company_check_severity_ship_manager_generic: string;
    company_check_severity_operator: string;
    company_check_severity_operator_sdn: string;
    company_check_severity_operator_generic: string;
    company_check_severity_registered_owner: string;
    company_check_severity_registered_owner_sdn: string;
    company_check_severity_registered_owner_generic: string;
    country_check_unknown_severity: string;
    country_check_severity: string;
    ship_sanction_check_severity: string;
    ship_sanction_check_severity_sdn: string;
    ship_sanction_check_severity_generic: string;
    ship_sanction_prior_months: 3;
    ship_sanction_prior_months_severity: string;
    port_visit_severity: string;
    no_ais_position_severity: string;
    zone_severity: string;
    ship_inspection_detained: string;
    ship_inspection_deficiency: string;

    constructor(screeningProfile: IScreeningProfileHttpResponse) {
        this.id = screeningProfile.id;
        this.name = screeningProfile.name;
        this.created = new Date(screeningProfile.created);
        this.modified = new Date(screeningProfile.modified);
        this.country_check_unknown_severity = screeningProfile.country_check_unknown_severity;
        this.url = screeningProfile.url;
        this.company_blacklists = screeningProfile.company_blacklists;
        this.port_blacklists = screeningProfile.port_blacklists;
        this.country_blacklists = screeningProfile.country_blacklists;
        this.ship_blacklists = screeningProfile.ship_blacklists;
        this.company_check_prior_months = screeningProfile.company_check_prior_months;
        this.company_check_prior_months_severity = screeningProfile.company_check_prior_months_severity;
        this.company_check_severity = screeningProfile.company_check_severity;
        this.company_check_severity_technical_manager = screeningProfile.company_check_severity_technical_manager;
        this.company_check_severity_technical_manager_sdn = screeningProfile.company_check_severity_technical_manager_sdn;
        this.company_check_severity_technical_manager_generic = screeningProfile.company_check_severity_technical_manager_generic;
        this.company_check_severity_group_beneficial_owner = screeningProfile.company_check_severity_group_beneficial_owner;
        this.company_check_severity_group_beneficial_owner_sdn = screeningProfile.company_check_severity_group_beneficial_owner_sdn;
        this.company_check_severity_group_beneficial_owner_generic = screeningProfile.company_check_severity_group_beneficial_owner_generic;
        this.company_check_severity_ship_manager = screeningProfile.company_check_severity_ship_manager;
        this.company_check_severity_ship_manager_sdn = screeningProfile.company_check_severity_ship_manager_sdn;
        this.company_check_severity_ship_manager_generic = screeningProfile.company_check_severity_ship_manager_generic;
        this.company_check_severity_operator = screeningProfile.company_check_severity_operator;
        this.company_check_severity_operator_sdn = screeningProfile.company_check_severity_operator_sdn;
        this.company_check_severity_operator_generic = screeningProfile.company_check_severity_operator_generic;
        this.company_check_severity_registered_owner = screeningProfile.company_check_severity_registered_owner;
        this.company_check_severity_registered_owner_sdn = screeningProfile.company_check_severity_registered_owner_sdn;
        this.company_check_severity_registered_owner_generic = screeningProfile.company_check_severity_registered_owner_generic;
        this.country_check_severity = screeningProfile.country_check_severity;
        this.ship_sanction_check_severity = screeningProfile.ship_sanction_check_severity;
        this.ship_sanction_check_severity_sdn = screeningProfile.ship_sanction_check_severity_sdn;
        this.ship_sanction_check_severity_generic = screeningProfile.ship_sanction_check_severity_generic;
        this.ship_sanction_prior_months = screeningProfile.ship_sanction_prior_months;
        this.ship_sanction_prior_months_severity = screeningProfile.ship_sanction_prior_months_severity;
        this.port_visit_severity = screeningProfile.port_visit_severity;
        this.no_ais_position_severity = screeningProfile.no_ais_position_severity;
        this.zone_severity = screeningProfile.zone_severity;
        this.ship_inspection_detained = screeningProfile.ship_inspection_detained;
        this.ship_inspection_deficiency = screeningProfile.ship_inspection_deficiency;
    }
}
